create table if not exists public.kiwify_access (
  id bigint generated by default as identity primary key,
  email text not null unique,
  status text not null default 'active',
  kiwify_transaction_id text,
  product_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.kiwify_access enable row level security;

create policy "No public access"
on public.kiwify_access
for all
to anon, authenticated
using (false)
with check (false);
